bookstores/bookstores/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include('users.urls',namespace='user')),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^',include('books.urls',namespace='books')),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^search/',include('haystack.urls'))
]

bookstores/cart/urls.py
from django.conf.urls import url

from cart import views
urlpatterns = [
   url(r'^add/$',views.cart_add,name='add'),
   url(r'^count/$',views.cart_count,name='count'),
   url(r'^$',views.cart_show,name='show'),
   url(r'^del/$',views.cart_del,name = 'delete'),
   url(r'^update/$',views.cart_update,name = 'update')
]

bookstores/order/urls.py
from django.conf.urls import url

from order import views
urlpatterns = [
   url(r'^place/$',views.order_place,name='place'),
   url(r'^commit/$',views.order_commit,name='commit'),
   url(r'^pay/$',views.order_pay,name='pay'),
   url(r'^check_pay/$',views.check_pay,name='check_pay'),
]

bookstores/cart/models.py
from django.db import models

# Create your models here.

bookstores/cart/views.py
from django.shortcuts import render

from django.http import JsonResponse
from books.models import Books
from utils.decorators import login_required
from django_redis import get_redis_connection

@login_required
def cart_add(request):
    books_id = request.POST.get('books_id')
    books_count = request.POST.get('books_count')

    if not all([books_id,books_count]):
        return JsonResponse({'res':1,'errmsg':'数据不完整'})

    books = Books.object.get_books_by_id(books_id=books_id)
    if books is None:
        return JsonResponse({'res':2,'errmsg':'商品不存在'})
    try:
        count = int(books_count)
    except Exception as e:
        return JsonResponse({'res':3,'errmsg':'商品数量必须为数字'})
    conn = get_redis_connection('default')
    cart_key = 'cart_%d' % request.session.get('passport_id')
    res = conn.hget(cart_key,books_id)
    if res is None:
        res = count
    else:
        res = int(res)+count
    if res>books.stock:
        return  JsonResponse({'res':4,'errmsg':'库存不足'})

    else:
        conn.hset(cart_key,books_id,res)

    return JsonResponse({'res':5})

@login_required
def cart_count(request):
    conn = get_redis_connection('default')
    cart_key = 'cart_%d' % request.session.get('passport_id')
    res = 0
    res_list =conn.hvals(cart_key)

    for i in res_list:
        res+=int(i)
    return JsonResponse({'res':res})

@login_required
def cart_show(request):
    passport_id = request.session.get('passport_id')
    conn = get_redis_connection('default')
    cart_key = 'cart_%d' % passport_id
    res_dict = conn.hgetall(cart_key)

    books_li =[]
    total_count = 0
    total_price = 0

    for books_id,count in res_dict.items():
        books = Books.object.get_books_by_id(books_id=books_id)
        books.count = count
        books.amout = int(count)*books.price
        books_li.append(books)

        total_count+=int(count)
        total_price+=int(count)*books.price

    context = {
        'books_li':books_li,
        'total_count':total_count,
        'total_price':total_price,

    }
    return render(request,'cart/cart.html',context)


@login_required
def cart_del(request):
    books_id = request.POST.get('books_id')

    if not all([books_id]):
        return JsonResponse({'res':1,'errmsg':'数据不完整'})
    books = Books.object.get_books_by_id(books_id=books_id)
    if books is None:
        return JsonResponse({'res':2,'errmsg':'商品不存在'})

    conn = get_redis_connection('default')
    cart_key = 'cart_%d' % request.session.get('passport_id')
    conn.hdel(cart_key,books_id)
    return JsonResponse({'res':3})



@login_required
def cart_update(request):
    books_id = request.POST.get('books_id')
    books_count = request.POST.get('books_count')
    if not all([books_id,books_count]):
        return  JsonResponse({'res':1,'errmsg':'数据不完整'})
    books=Books.object.get_books_by_id(books_id=books_id)
    if books is None:
        return JsonResponse({'res':2,'errmsg':'商品不存在'})

    try:
        books_count = int(books_count)

    except Exception as e:
        return JsonResponse({'res':3,'errmsg':'商品数目必须为数字'})

    conn = get_redis_connection('default')
    cart_key = 'cart_%d' % request.session.get('passport_id')
    if books_count>books.stock:
        return JsonResponse({'res':4,'errmsg':'商品库存不足'})
    conn.hset(cart_key,books_id,books_count)
    return JsonResponse({'res':5})

bookstores/templates/cart/cart.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body %}

	<div class="total_count">全部商品<em>2</em>件</div>	
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form method="post" action="{% url 'order:place' %}">
    {% for book in books_li %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="books_ids" value="{{ book.id }}" checked></li>
		<li class="col02"><img src="{% static book.image %}"></li>
		<li class="col03">{{ book.name }}<br><em>{{ book.price }}元/{{ book.unit }}</em></li>
		<li class="col04">{{ book.unit }}</li>
		<li class="col05">{{ book.price }}</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" books_id="{{ book.id }}" class="num_show fl" value="{{ book.count }}">
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">{{ book.amount }}</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>

	{% endfor %}
	

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_price }}</em><br>共计<b>{{ total_count }}</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>
    {% csrf_token %}
	</ul>
</form>
{% endblock %}
{% block topfiles %}
    <script>
    $(function () {
        update_cart_count()
        update_total_price()
          function update_cart_count() {
         $.get('/cart/count/',function (data) {
             $('.total_count').children('em').text(data.res)
             $('#show_count').html(data.res)
         })



     }
        function update_total_price() {
            total_count=0
            total_price =0
            $('.cart_list_td').find(':checked').parents('ul').each(function () {
                res_dict = update_books_price($(this))
                total_count+=res_dict.books_count
                total_price+=res_dict.books_amount
            })
            $('.settlements').find('em').text(total_price.toFixed(2))
            $('.settlements').find('b').text(total_count)

        }
     function update_books_price(books_ul) {
         books_price = books_ul.children('.col05').text()
         books_count = books_ul.find('.num_show').val()

         books_price = parseFloat(books_price)
         books_count = parseInt(books_count)
         books_amount = books_price*books_count

         books_ul.children('.col07').text(books_amount.toFixed(2)+'元')
         return {
             'books_count':books_count,
             'books_amount':books_amount
         }

     }

     $('.cart_list_td').children('.col08').children('a').click(function () {
         books_ul = $(this).parents('ul')
         books_id = books_ul.find('.num_show').attr('books_id')
         csrf = $('input[name="csrfmiddlewaretoken"]').val()
         params ={
             'books_id':books_id,
             'csrfmiddlewaretoken':csrf
         }
      $.post('/cart/del/',params,function (data) {
          if (data.res==3){
              books_ul.remove()
              is_checked = books_ul.find(':checkbox').prop('checked')
              if(is_checked){
                  update_total_price()
              }
              update_cart_count()
              $('.settlements').find(":checkbox").prop('checked',false)
          }
      })
     })
        $('.settlements').find(':checkbox').change(function () {
            is_checked =$(this).prop('checked')
            $('.cart_list_td').find(':checkbox').each(function () {
              $(this).prop('checked',is_checked)
            })
            update_total_price()
        })
        $('.cart_list_td').find(':checkbox').change(function () {
            all_len = $('.cart_list_td').find(':checkbox').length
            checked_len = $('.cart_list_td').find(':checked').length
            if (checked_len < all_len){
                $('.settlements').find(':checkbox').prop('checked',false)

            }
            else {
                $('.settlements').find(':checkbox').prop('checked',true)
            }
            update_total_price()
        })
        $('.add').click(function () {
            books_count = $(this).next().val()
            books_id = $(this).next().attr('books_id')
            books_count = parseInt(books_count)+1
            update_remote_cart_info(books_id,books_count)
            if(error_update==false){
                $(this).next().val(books_count)
                is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
                if (is_checked){
                    update_total_price()
                }
                else {
                    update_books_price($(this).parents('ul'))

                }
                update_cart_count()

            }


        })

        $('.minus').click(function () {
            books_count = $(this).prev().val()
            books_id = $(this).prev().attr('books_id')
            books_count = parseInt(books_count)-1
            if (books_count <=0){
                books_count =1
            }
            update_remote_cart_info(books_id,books_count)
            if (error_update==false){
                $(this).prev().val(books_count)
                is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
                if (is_checked){
                    update_total_price()
                }
                else {
                    update_books_price($(this).parents('ul'))
                }
                update_cart_count()
            }
        })
        pre_books_count = 0
        $('.num_show').focus(function () {
            pre_books_count = $(this).val()
        
        })
        
        $('.num_show').blur(function () {
            books_count=$(this).val()
            books_id = $(this).attr('books_id')
            if (isNaN(books_count)||books_count.trim().length==0||parseInt(books_count)<=0){
                $(this).val(pre_books_count)
                return
            }
            books_count = parseInt(books_count)
            update_remote_cart_info(books_id,books_count)
            if(error_update==false){
                $(this).val(books_count)
                is_checked=$(this).parents('ul').find(':checkbox').prop('checked')
                if (is_checked){
                    update_total_price()
                }
                else {
                    update_books_price($(this).parents('ul'))
                }
                update_cart_count()
            }
            else {
                $(this).val(pre_books_count)
            }
        })
        error_update = false
        function update_remote_cart_info(books_id,books_count) {
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            params = {
                'books_id':books_id,
                'books_count':books_count,
                'csrfmiddlewaretoken':csrf
            }
            $.ajaxSettings.async = false
            $.post('/cart/update/',params,function (data) {
                if (data.res ==5){
                    error_update =false
                }
                else {
                    error_update = true
                    alert(data.errmsg)
                }
            })

         $.ajaxSettings.async=true
        }
    })
    </script>

	{% endblock %}