bookstores/books/urls.py
from django.conf.urls import url

from books import views
urlpatterns = [
   url(r'^$',views.index,name='index'),
   url(r'books/(?P<books_id>\d+)/$',views.detail,name='detail'),
   url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)/$',views.list,name='list')

]

bookstores/bookstores/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include('users.urls',namespace='user')),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^',include('books.urls',namespace='books')),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^search/',include('haystack.urls'))
]

bookstores/cart/urls.py
from django.conf.urls import url

from cart import views
urlpatterns = [
   url(r'^add/$',views.cart_add,name='add'),
   url(r'^count/$',views.cart_count,name='count'),
   url(r'^$',views.cart_show,name='show'),
   url(r'^del/$',views.cart_del,name = 'delete'),
   url(r'^update/$',views.cart_update,name = 'update')
]

bookstores/books/models.py
from django.db import models

from db.base_model import BaseModel
from tinymce.models import HTMLField
from books.enums import *

class BooksManager(models.Manager):
    def get_books_by_type(self,type_id,limit=None,sort='default'):

        if sort=='new':
            order_by=('-create_time',)
        elif sort== 'hot':
            order_by=('-sales',)
        elif sort=='price':
            order_by=('price',)
        else:
            order_by=('-pk',)
        books_li = self.filter(type_id=type_id).order_by(*order_by)
        if limit:
            books_li = books_li[:limit]
        return books_li
    def get_books_by_id(self,books_id):
        try:
            books= self.get(id=books_id)
        except self.model.DoesNotExist:
            books=None
        return books

class Books(BaseModel):
    books_type_choice=((k,v) for k,v in BOOKS_TYPE.items())
    status_choice=((k,v) for k,v in STATUS_CHOICE.items())
    type_id=models.SmallIntegerField(default=PYTHON,choices=books_type_choice,verbose_name='商品种类')
    name=models.CharField(max_length=20,verbose_name='商品名称')
    desc= models.CharField(max_length=128,verbose_name='商品简介')
    price=models.DecimalField(max_digits=10,decimal_places=2,verbose_name='商品价格')
    unit=models.CharField(max_length=20,verbose_name='商品单位')
    stock = models.IntegerField(default=1,verbose_name='商品库存')
    sales = models.IntegerField(default=0,verbose_name='商品销量')
    detail = HTMLField(verbose_name='商品详情')
    image= models.ImageField(upload_to='books',verbose_name='商品图片')
    status = models.SmallIntegerField(default=ONLINE,choices=status_choice,verbose_name='商品状态')

    object=BooksManager()

    def __str__(self):
        return self.name

    class Meta:
        db_table='s_books'
        verbose_name='书籍'
        verbose_name_plural='书籍'

bookstores/books/views.py
from django.shortcuts import render,redirect

from books.models import Books
from books.enums import *
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator
from django.views.decorators.cache import cache_page
from django_redis import get_redis_connection
@cache_page(60*15)
def index(request):
    python_new = Books.object.get_books_by_type(PYTHON,limit=3,sort='new')
    python_hot=Books.object.get_books_by_type(PYTHON,limit=4,sort='hot')
    javascript_new = Books.object.get_books_by_type(JAVASCRIPT,limit=3,sort='new')
    javascript_hot = Books.object.get_books_by_type(JAVASCRIPT,limit=4,sort='hot')
    algorithms_new = Books.object.get_books_by_type(ALGORITHMS,3,sort='new')
    algorithms_hot=Books.object.get_books_by_type(ALGORITHMS,4,sort='hot')
    machinelearning_new=Books.object.get_books_by_type(MACHINELEARNING,3,sort='new')
    machinelearning_hot = Books.object.get_books_by_type(MACHINELEARNING,4,sort='hot')
    operatingsystem_new=Books.object.get_books_by_type(OPERATINGSYSTEM,3,sort='new')
    operatingsystem_hot=Books.object.get_books_by_type(OPERATINGSYSTEM,4,sort='hot')
    database_new=Books.object.get_books_by_type(DATABASE,3,sort='new')
    database_hot=Books.object.get_books_by_type(DATABASE,4,sort='hot')
    context={
        'python_new':python_new,
        'python_hot':python_hot,
        'javascript_new': javascript_new,
        'javascript_hot': javascript_hot,
        'algorithms_new': algorithms_new,
        'algorithms_hot': algorithms_hot,
        'machinelearning_new': machinelearning_new,
        'machinelearning_hot': machinelearning_hot,
        'operatingsystem_new': operatingsystem_new,
        'operatingsystem_hot': operatingsystem_hot,
        'database_new': database_new,
        'database_hot': database_hot,

    }
    return render(request,'books/index.html',context)

def detail(request,books_id):
    books = Books.object.get_books_by_id(books_id=books_id)

    if books is None:
        return redirect(reverse('books:index'))
    books_li=Books.object.get_books_by_type(type_id=books.type_id,limit=2,sort='new')
    type_title = BOOKS_TYPE[books.type_id]
    if request.session.has_key("islogin"):
        con = get_redis_connection('default')
        key = 'history_%d' % request.session.get('passport_id')
        con.lrem(key, 0, books.id)
        con.lpush(key,books.id)
        con.ltrim(key,0,4)


    context = {'books':books,'books_li':books_li,'type_title':type_title}

    return render(request,'books/detail.html',context)

def list(request,type_id,page):
    sort=request.GET.get('sort','default')

    if int(type_id) not in BOOKS_TYPE.keys():
        return redirect(reverse('books:index'))

    books_li = Books.object.get_books_by_type(type_id=type_id,sort=sort)


    paginator = Paginator(books_li,1)
    num_pages= paginator.num_pages
    if page =='' or int(page)>num_pages:
        page=1
    else:
        page = int(page)
    books_li = paginator.page(page)
    if num_pages <5:
        pages = range(1,num_pages+1)
    elif page <=3:
        pages = range(1,6)

    elif num_pages - page <=2:
        pages = range(num_pages-4,num_pages+1)

    else:
        pages=range(page-2,page+3)

    books_new = Books.object.get_books_by_type(type_id=type_id,limit=2,sort='new')
    type_title = BOOKS_TYPE[int(type_id)]
    context={
        'books_li': books_li,
        'books_new': books_new,
        'type_id': type_id,
        'sort': sort,
        'type_title': type_title,
        'pages': pages
    }
    return render(request,'books/list.html',context)

bookstores/templates/books/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书店-首页{% endblock %}
{% block body %}


	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="python">Python</a></li>
					<li><a href="#" class="javascript">Javascript</a></li>
					<li><a href="#" class="algorithms">数据结构与算法</a></li>
					<li><a href="#" class="machinelearning">机器学习</a></li>
					<li><a href="#" class="operatingsystem">操作系统</a></li>
					<li><a href="#" class="database">数据库</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">Python</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="book_detail_con clearfix">
		<div class="book_detail_pic fl"><img src="{% static 'images/book_detail.jpg' %}"></div>

		<div class="book_detail_list fr">
			<h3>{{ books.name }}</h3>
			<p>{{ books.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ books.price }}</em></span>
				<span class="show_unit">单  位：{{ books.unit }}</span>
			</div>
			<div class="book_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div class="total">总价：<em>100元</em></div>
			<div class="operate_btn">
                {% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" books_id="{{ books.id }}" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_book">
				<h3>新品推荐</h3>
				<ul>
                    {% for book in books_li %}
					<li>
						<a href="{% url 'books:detail' books_id=books.id%}"><img src="{% static 'images/book/book001.jpg' %}"></a>
						<h4><a href="{% url 'books:detail' books_id=books.id%}">{{ books.name }}</a></h4>
						<div class="price">￥{{ books.price }}</div>
					</li>
				  {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ books.detail |safe }}</dd>
				</dl>
			</div>

		</div>
	</div>
<div class="add_jump"></div>
    <script type="text/javascript">
    $('#add_cart').click(function () {
        var books_id = $(this).attr('books_id');
        var books_count=$('.num_show').val();
        var csrf = $('input[name="csrfmiddlewaretoken"]').val();
        var params = {
            'books_id':books_id,
            'books_count':books_count,
            'csrfmiddlewaretoken':csrf,
        }
        $.post('/cart/add/',params,function (data) {
            if (data.res ==5){
                var count = $('#show_count').html();
                var count = parseInt(count)+parseInt(books_count);
                $('#show_count').html(count);
            }else {
                alert(data.errmsg)
            }
        })
    })

    </script>

	<div class="add_jump"></div>

{% endblock %}
{% block topfiles %}
    <script>
    $(function () {
        update_total_price()
        function update_total_price() {
            books_price = $('.show_pirze').children('em').text()
            books_count  = $('.num_show').val()
            books_price=parseFloat(books_price)
            books_count = parseInt(books_count)
            total_price = books_price*books_count
            $('.total').children('em').text(total_price.toFixed(2)+'元')
        }
        $('.add').click(function () {
        books_count=$('.num_show').val()
        books_count=parseInt(books_count)+1
        $('.num_show').val(books_count)
        update_total_price()
        })
        $('.minus').click(function () {
            books_count = $('.num_show').val()
            books_count=parseInt(books_count)-1
            if (books_count==0){
                books_count=1
            }
            $('.num_show').val(books_count)
            update_total_price()
        })
        $('.num_show').blur(function () {
            books_count = $(this).val()
            if (isNaN(books_count) || books_count.trim().length==0 || parseInt(books_count)<=0){
                books_count =1
            }
        })
        $('.num_show').val(parseInt(books_count))
        update_total_price()
    })


    </script>
{% endblock %}

bookstores/templates/books/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书店-首页{% endblock %}
{% block body %}





	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="python">Python</a></li>
			<li><a href="#model02" class="javascript">Javascript</a></li>
			<li><a href="#model03" class="algorithms">数据结构与算法</a></li>
			<li><a href="#model04" class="machinelearning">机器学习</a></li>
			<li><a href="#model05" class="operatingsystem">操作系统</a></li>
			<li><a href="#model06" class="database">数据库</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="{% static 'images/slide.jpg' %}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="{% static 'images/slide02.jpg' %}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="{% static 'images/slide03.jpg' %}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="{% static 'images/slide04.jpg' %}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="{% static 'images/adv01.jpg' %}" style="width: 240px; height: 135px;"></a>
			<a href="#"><img src="{% static 'images/adv02.jpg' %}" style="width: 240px; height: 135px;"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">Python</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in python_new %}
                    <a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a>
                {% endfor %}

			</div>
			<a href="{% url 'books:list' type_id=1 page=1 %}" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner01.jpg' %}"></div>
			<ul class="book_list fl">
                {% for book in python_hot %}
                    <li>
					<h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
					<a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"></a>
					<div class="prize">{{ book.price }}</div>
				</li>
                {% endfor %}

			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">Javascript</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in javascript_new %}
				<a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }} %}</a>
							{% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner02.jpg' %}"></div>
			<ul class="book_list fl">
				{% for book in javascript_hot %}
                <li>
					<h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
					<a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				</li>
               {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">数据结构与算法</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in algorithms_new %}
				<a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner03.jpg' %}"></div>
			<ul class="book_list fl">
                {% for book in algorithms_hot %}
				<li>
					<h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
					<a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"></a>
					<div class="price">¥ {{ book.price }}</div>
				</li>
			  {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">机器学习</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in machinelearning_new %}
				<a href="#">{{ book.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner04.jpg' %}"></div>
			<ul class="book_list fl">
				{% for book in machinelearning_hot %}
                <li>
					<h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
					<a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				</li>
			    {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">操作系统</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in operatingsystem_new %}
				<a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner05.jpg' %}"></div>
			<ul class="book_list fl">
				{% for book in operatingsystem_hot %}
                <li>
					<h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
					<a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				</li>
				 {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">数据库</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in database_new %}
				<a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner06.jpg' %}"></div>
			<ul class="book_list fl">
				{% for book in database_hot %}
                <li>
					<h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
					<a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>



{% endblock %}

bookstores/templates/books/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书店-商品列表{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}

    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>   
                <span></span>           
                <ul class="subnav">
                    <li><a href="#" class="python">Python</a></li>
                    <li><a href="#" class="javascript">Javascript</a></li>
                    <li><a href="#" class="algorithms">数据结构与算法</a></li>
                    <li><a href="#" class="machinelearning">机器学习</a></li>
                    <li><a href="#" class="operatingsystem">操作系统</a></li>
                    <li><a href="#" class="database">数据库</a></li>
                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">移动端书城</a></li>
                <li class="interval">|</li>
                <li><a href="">秒杀</a></li>
            </ul>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="#">全部分类</a>
        <span>></span>
        <a href="#">{{ type_title }}</a>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_book">
                <h3>新品推荐</h3>
                <ul>
                    {% for book in books_new %}
                    <li>
                        <a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"></a>
                        <h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
                        <div class="prize">￥{{ book.price }}</div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <div class="sort_bar">
                <a href="/list/{{ type_id }}/1/" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
                <a href="/list/{{ type_id }}/1/?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
                <a href="/list/{{ type_id }}/1/?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
            </div>

            <ul class="book_type_list clearfix">
                {% for book in books_li %}
                    <li>
                        <a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"></a>
                        <h4><a href="{% url 'books:detail' books_id=book.id %}">{{ books.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ book.price }}</span>
                            <span class="unit">{{ book.unit }}</span>
                            <a href="#" class="add_books" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}
            </ul>

            <div class="pagenation">
                {% if books_li.has_previous %}
                    <a href="/list/{{ type_id }}/{{ books_li.previous_page_number }}/?sort={{ sort }}"><上一页</a>
                {% endif %}
                {% for pindex in pages %}
                    {% if pindex == books_li.number %}
                        <a href="/list/{{ type_id }}/{{ pindex }}/?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
                        <a href="/list/{{ type_id }}/{{ pindex }}/?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}
                {% if books_li.has_next %}
                    <a href="/list/{{ type_id }}/{{ books_li.next_page_number }}/?sort={{ sort }}">下一页></a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock body %}