bookstores/books/urls.py
from django.conf.urls import url

from books import views
urlpatterns = [
   url(r'^$',views.index,name='index'),
   url(r'books/(?P<books_id>\d+)/$',views.detail,name='detail'),
   url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)/$',views.list,name='list')

]

bookstores/bookstores/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include('users.urls',namespace='user')),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^',include('books.urls',namespace='books')),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^search/',include('haystack.urls'))
]

bookstores/cart/urls.py
from django.conf.urls import url

from cart import views
urlpatterns = [
   url(r'^add/$',views.cart_add,name='add'),
   url(r'^count/$',views.cart_count,name='count'),
   url(r'^$',views.cart_show,name='show'),
   url(r'^del/$',views.cart_del,name = 'delete'),
   url(r'^update/$',views.cart_update,name = 'update')
]

bookstores/users/urls.py
from django.conf.urls import url
from users import views

urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^register_handle/$',views.register_handle,name='register_handle'),
    url(r'^login/$',views.login,name='login'),
    url(r'^login_check/$',views.login_check,name='login_check'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^$',views.user,name='usr'),
    url(r'^address/$',views.address,name='address'),
    url(r'^order/(?P<page>\d+)?/?$',views.order,name='order'),
    url(r'^verifycode/$',views.verifycode,name='verifycode'),
    url(r'active/(?P<token>.*)/$',views.register_active,name='active'),
]

bookstores/users/models.py
from db.base_model import BaseModel
from django.db import models

from utils.get_hash import get_hash
class PassportManager(models.Manager):
    def add_one_passport(self,username,password,email):
         passport = self.create(username=username,password=get_hash(password),email=email)
         return passport

    def get_one_passport(self,username,password):
        try:
            passport = self.get(username=username,password=get_hash(password))
        except self.model.DoesNotExist:
            passport = None
        return passport

    def check_passport(self,username):
        try:
            passport=self.get(username=username)
        except self.model.DoesNotExist:
            passport = None
        if passport:
            return True
        return False

class Passport(BaseModel):
    username = models.CharField(max_length=20,unique=True,verbose_name='用户名称')
    password = models.CharField(max_length=40,verbose_name='用户密码')
    email = models.EmailField(verbose_name='用户邮箱')
    is_active = models.BooleanField(default=False,verbose_name='激活状态')

    objects = PassportManager()

    class Meta:
        db_table = 's_user_account'

class AddressManager(models.Manager):
    def get_default_address(self,passport_id):
        try:
            addr = self.get(passport_id=passport_id,is_default=True)

        except self.model.DoesNotExist:
            addr=None
        return addr

    def get_one_address(self,passport_id,recipient_name,recipient_addr,zip_code,recipient_phone):
        addr = self.get_default_address(passport_id=passport_id)
        if addr:
            is_default=False
        else:
            is_default=True
        addr = self.create(passport_id=passport_id,
                           recipient_name=recipient_name,
                           recipient_addr=recipient_addr,
                           zip_code=zip_code,
                           recipient_phone=recipient_phone,

                           is_default=is_default
                           )
        return addr
class Address(BaseModel):
    recipient_name = models.CharField(max_length=20,verbose_name='收件人')
    recipient_addr = models.CharField(max_length=256,verbose_name='收件地址')
    zip_code=models.CharField(max_length=6,verbose_name='邮政编码')
    recipient_phone = models.CharField(max_length=11,verbose_name='联系电话')
    is_default = models.BooleanField(default=False,verbose_name='是否默认')
    passport = models.ForeignKey('Passport',verbose_name='账户')

    objects = AddressManager()

    class Meta:
        db_table='s_user_address'

bookstores/users/views.py
import os


from django.core.paginator import Paginator
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render,reverse,redirect
from users.tasks import send_active_email

from bookstores import settings
from order.models import OrderInfo, OrderBooks
from users.models import Passport,Address
from utils.decorators import login_required
import re
import redis
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import SignatureExpired
from django_redis import get_redis_connection
from books.models import Books
def register(request):
    return render(request,'users/register.html')

def register_handle(request):
    username = request.POST.get('user_name')
    password = request.POST.get('pwd')
    email = request.POST.get('email')

    if not all([username,password,email]):
        return render(request,'users/register.html',{'errmsg': '参数不能为空!'})

    if not re.match(r'^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):
        return render(request,'users/register.html',{'errmsg':'邮箱不合法！'})

    try:
        passport = Passport.objects.add_one_passport(username=username, password=password, email=email)
    except Exception as e:
        print('e: ',e)
        return render(request,'users/register.html',{'errmsg':'用户名已经存在！'})
    serializer = Serializer(settings.SECRET_KEY,3600)
    token = serializer.dumps({'confirm':passport.id})
    token = token.decode()
    send_active_email.delay(token,username,email)
    return redirect(reverse('books:index'))


def login(request):
    if request.COOKIES.get('username'):
        username = request.COOKIES.get('username')
        checked='checked'
    else:
        username=''
        checked =''
    context={
        'username':username,
        'checked':checked,
    }
    return render(request,'users/login.html',context)

def login_check(request):
    username=request.POST.get('username')
    password =request.POST.get('password')
    remember=request.POST.get('remember')
    verifycode = request.POST.get('verifycode')
    if not all([username,password,remember,verifycode]):
        return  JsonResponse({'res':2})
    if verifycode.upper()!=request.session['verifycode']:
        return JsonResponse({'res':2})
    passport=Passport.objects.get_one_passport(username=username,password=password)
    if passport:
        next_url = reverse('books:index')
        jres=JsonResponse({'res':1,'next_url':next_url})

        if remember=='true':
            jres.set_cookie('username',username,max_age=7*24*3600)
        else:
            jres.delete_cookie('username')

        request.session['islogin']=True
        request.session['username']=username
        request.session['passport_id']=passport.id
        cache_clean()
        return jres
    else:
        return JsonResponse({'res':0})

def logout(request):
    request.session.flush()
    cache_clean()
    return redirect(reverse('books:index'))
def cache_clean():
    r = redis.StrictRedis(host='localhost',port=6379,db=2)
    for key in r.keys():
        if 'bookstores-index' in key.decode('utf8'):
            print('key:',key)
            r.delete(key)
@login_required
def user(request):
    passport_id =request.session.get('passport_id')
    addr = Address.objects.get_default_address(passport_id=passport_id)
    con = get_redis_connection('default')
    key = "history_%d"%passport_id
    history_li = con.lrange(key,0,4)

    books_li=[]
    print(history_li)
    for id in history_li:
        books = Books.object.get_books_by_id(books_id=id)
        books_li.append(books)
    context ={
        'addr':addr,
        'page':'user',
        'books_li':books_li,

    }
    return render(request,'users/user_center_info.html',context)

@login_required
def address(request):
    passport_id = request.session.get('passport_id')
    if request.method =='GET':
        addr = Address.objects.get_default_address(passport_id=passport_id)
        return  render(request,'users/user_center_site.html',{'addr':addr,'address':'address'})
    else:
        recipient_name = request.POST.get('username')
        recipient_addr = request.POST.get('addr')
        zip_code = request.POST.get('zip_code')
        recipient_phone = request.POST.get('phone')
        if not all([recipient_name,recipient_addr,recipient_phone]):
            return render(request,'users/user_center_site.html',{'errmsg':'参数不能为空'})

        Address.objects.get_one_address(passport_id=passport_id,
                                        recipient_name=recipient_name,
                                        recipient_addr=recipient_addr,
                                        recipient_phone=recipient_phone,
                                        zip_code=zip_code
                                        )
        return redirect(reverse('user:address'))


@login_required
def order(request,page):
    passport_id = request.session.get('passport_id')
    order_li = OrderInfo.objects.filter(passport_id=passport_id)
    for order in order_li:
        order_id = order.order_id
        order_books_li = OrderBooks.objects.filter(order_id=order_id)
        for order_books in order_books_li:
            count = order_books.count
            price = order_books.price
            amount = count *price
            order_books.amount =amount
        order.order_books_li = order_books_li
    paginator = Paginator(order_li,3)
    num_pages = paginator.num_pages

    if not page:
        page=1
    if page =='' or int(page)>num_pages:
        page = 1
    else:
        page = int(page)
    order_li = paginator.page(page)

    if num_pages<5:
        pages = range(1,num_pages+1)
    elif page<=3:
        pages = range(1,6)
    elif num_pages-page <=2:
        pages= range(num_pages-4,num_pages+1)
    else:
        pages=range(page-2,page+3)
    context = {
        'order_li':order_li,
        'pages':pages,
    }

    return render(request,'users/user_center_order.html',context)

def verifycode(request):
    from PIL import Image,ImageDraw,ImageFont
    import random
    bgcolor = (random.randrange(20,100),random.randrange(20,100),255)
    width = 100
    height =25
    im = Image.new('RGB',(width,height),bgcolor)
    draw=ImageDraw.Draw(im)
    for i in range(0,100):
        xy=(random.randrange(0,width),random.randrange(0,height))
        fill = (random.randrange(0,255),255,random.randrange(0,255))
        draw.point(xy,fill=fill)
        str1='ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
        rand_str=''
        for i in range(0,4):
            rand_str+=str1[random.randrange(0,len(str1))]
        font = ImageFont.truetype(os.path.join(settings.BASE_DIR,'Ubuntu-RI.ttf'),15)
        fontcolor = (255,random.randrange(0,255),random.randrange(0,255))
        draw.text((5,2),rand_str[0],font=font,fill=fontcolor)
        draw.text((25,2),rand_str[1],font=font,fill=fontcolor)
        draw.text((50,2),rand_str[2],font=font,fill=fontcolor)

        draw.text((75,2),rand_str[3],font=font,fill=fontcolor)
        del draw
        request.session['verifycode']=rand_str
        import io
        buf = io.BytesIO()
        im.save(buf,'png')
        return HttpResponse(buf.getvalue(),'image/png')

def register_active(request,token):
    serializer = Serializer(settings.SECRET_KEY,3600)
    try:
        info=serializer.loads(token)
        passport_id = info['confirm']
        passport = Passport.objects.get(id=passport_id)
        passport.is_active=True
        passport.save()
        return redirect(reverse('user:login'))
    except SignatureExpired:
        return HttpResponse('激活链接已过期')

bookstores/templates/users/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-登录{% endblock title %}
{% block topfiles %}
<script>
    $(function () {
        $('#btnLogin').click(function () {
            // 获取用户名和密码
            var username = $('#username').val()
            var password = $('#pwd').val()
            var csrf = $('input[name="csrfmiddlewaretoken"]').val()
            var remember = $('input[name="remember"]').prop('checked')
            var vc = $('input[name="vc"]').val()
            // 发起ajax请求
            var params = {
                'username': username,
                'password': password,
                'csrfmiddlewaretoken': csrf,
                'remember': remember,
                'verifycode':vc,
            }
            $.post('/user/login_check/', params, function (data) {
                // 用户名密码错误 {'res':0}
                // 登录成功 {'res':1}
                if (data.res == 0){
                    $('#username').next().html('用户名或密码错误').show()
                }
                else
                {
                    // 跳转页面
                    location.href = data.next_url // /user/
                }
            })
        })
    })
</script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="login_top clearfix">
        <a href="{% url 'books:index' %}" class="login_logo"><img src="{% static 'images/logo.png' %}" style="width: 160px; height: 53px;"></a>
    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">学计算机 · 来尚硅谷</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登录</h1>
                    <a href="{% url 'user:register' %}">立即注册</a>
                </div>
                <div class="form_input">
                    {% csrf_token %}
                    <input type="text" id="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
                    <div class="user_error">输入错误</div>
                    <input type="password" id="pwd" class="pass_input" placeholder="请输入密码">
                    <div class="pwd_error">输入错误</div>
                    <div class="more_input clearfix">
                        <input type="checkbox" name="remember" {{ checked }}>
                        <label>记住用户名</label>
                        <a href="#">忘记密码</a>
                    </div>
                    <div style="top:100px;position:absolute;">
                        <input type="text" id="vc" name="vc">
                        <img src="/user/verifycode/" onclick="this.src='/user/verifycode/?'+Math.random()" alt="CheckeCode" id="verifycode"/>
                    </div>
                    <input type="button" id="btnLogin" value="登录" class="input_submit">
                </div>
            </div>
        </div>
    </div>
{% endblock body %}
{% block cart_count %}{% endblock %}

bookstores/templates/users/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-注册{% endblock %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo.png' %}" style="width: 160px; height: 53px;"></a>
			<div class="reg_slogan">学计算机  ·  来尚硅谷</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="{% url 'user:register_handle' %}">
				{% csrf_token %}
                    {{ errmsg }}
                    <ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”尚硅谷书城用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>


	
{% endblock %}
{% block cart_count %}{% endblock %}

bookstores/templates/users/user_center_info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}用户中心{% endblock %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:usr' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ request.session.username }}</li>
							{% if addr %}
                            <li><span>联系方式：</span>{{ addr.recipient_phone }}</li>
							<li><span>联系地址：</span>{{ addr.recipient_addr }}</li>
                            {% else %}
                                 <li><span>联系方式：</span>无</li>
							<li><span>联系地址：</span>无</li>
                            {% endif %}
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="book_type_list clearfix">
				{% for books in books_li %}
                        <li>
					<a href="{% url 'books:detail' books_id=books.id%}"><img src="{% static books.image %}"></a>
					<h4><a href="{% url 'books:detail' books_id=books.id%}">{{ books.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ books.price }}</span>
						<span class="unit">{{ books.unit }}</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>
			    {% endfor %}
			</ul>
		</div>
		</div>
	</div>
{% endblock %}



	

bookstores/templates/users/user_center_order.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load filters %}
{% block title %}尚硅谷书店-订单{% endblock %}
{% block topfiles %}{% endblock %}

{% block body %}




	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:usr' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
        {% for order in order_li %}
				<ul class="order_list_th w978 clearfix">
                    {% csrf_token %}
					<li class="col01">{{ order.create_time }}</li>
					<li class="col02">订单号：{{ order.order_id }}</li>
					<li class="col02 stress">{{ order.status }}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for order_book in order.order_books_li %}
								<ul class="order_book_list clearfix">					
									<li class="col01"><img src="{% static order_book.books.image %}"></li>
									<li class="col02">{{ order_book.books.name }}<em>{{ order_book.books.price }}元/册</em></li>
									<li class="col03">{{ order_book.count }}</li>
									<li class="col04">{{ order_book.amount }}元</li>
								</ul>
						       {% endfor %}
							</td>
							<td width="15%">{{ order.total_price }}元</td>
							<td width="15%">{{ order.status | order_status}}</td>
							<td width="15%"><a href="#" class="oper_btn" pay_method="{{ order.pay_method }}" order_id="{{ order.order_id }}" order_status="{{ order.status }}">去付款</a></td>
						</tr>
					</tbody>
				</table>
				{% endfor %}



				<div class="pagenation">
                    {% if order_li.has_previous %}
					<a href="{% url 'user:order' page=order_li.previous_page_number %}">上一页</a>
					{% endif %}
                    {% for page in pages %}
                        {% if page == order_li.number %}
                            <a href="{% url 'user:order' page=page %}" class="active">{{ page }}</a>
                        {% else %}
                            <a href="{% url 'user:order' page=page %}" >{{ page }}</a>

                        {% endif %}
         {% endfor %}
                   {% if order_li.has_next %}
					    <a href="#{% url 'user:order' page=order_li.next_page_number %}">下一页</a>
                   {% endif %}
				</div>

		</div>
	</div>

{% endblock %}
{% block bottomfiles %}
    <script>
    $(function () {
       $('.oper_btn').click(function () {
        order_id = $(this).attr('order_id')
        order_status = $(this).attr('order_status')
        csrf = $('input[name="csrfmiddlewaretoken"]').val()
        params={'order_id':order_id,'csrfmiddlewaretoken':csrf}
        if (order_status==1){
            $.post('/order/pay/',params,function (data) {
                if(data.res==3){
                    window.open(data.pay_url)
                    $.post('/order/check_pay/',params,function (data) {
                        if(data.res==3){
                            alert('支付成功')
                            location.reload()
                        }
                        else {
                            alert(data.errmsg)
                        }
                    })
                }
                else{
                    alert(data.errmsg)
                }
            })
        }
    })
    })

    </script>
{% endblock %}

bookstores/templates/users/user_center_site.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block topfiles %}
{% endblock topfiles %}

{% block title %}书城用户中心-我的地址{% endblock %}
{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:usr' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                        {% if addr %}
						<dd>{{ addr.recipient_addr }} ({{ addr.recipient_name }}收) {{ addr.recipient_phone }}</dd>
					   {% else %}
                        <dd>无</dd>
                        {% endif %}
                    </dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="{% url 'user:address' %}">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="username">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>

						<input type="submit"value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{% endblock %}



	